language: scala
scala:
- 2.11.6
jdk:
  - oraclejdk8
install:
  - IDEA_VERSION=13.1.6
  - IDEA_TAR=ideaIC-${IDEA_VERSION}.tar.gz
  - |
    if [ -f ~/$IDEA_TAR ]; then
        echo "Copying existing IDEA archive."
        cp ~/$IDEA_TAR .
    else
        echo "Downloading IDEA archive."
        travis_retry wget http://download.jetbrains.com/idea/$IDEA_TAR -P ~
        echo "Copying IDEA archive."
        cp ~/$IDEA_TAR .
    fi
  - rm -rf idea-IC-*
  - echo "Installing IDEA to idea-IC/"
  - tar zxf $IDEA_TAR
  - rm -rf $IDEA_TAR
  - mv idea-IC-* idea-IC
  - echo "$(pwd)/idea-IC"
services:
 
env:
  - PR_VALIDATE=1
  - PR_VALIDATE=0

script:
  - IDEA_LIB="$(pwd)/idea-IC/lib" bin/run_tests.sh

notifications:
  email: true
